### ISSUE TITLE
How to deploy a custom tokenmapper in a production Keycloak?

### ISSUE THREAD

**Issue by wimdeblauwe** [dasniko/keycloak-tokenmapper-example#1]
Very interesting video and sample code, thanks for that. I wonder how I should deploy this to a Keycloak instance? Should the resulting JAR file be put somewhere? Is that enough or are there other configuration files that need to change?

**Comment by dasniko** [comment]
Thanks.
See docs for depoyment: https://www.keycloak.org/docs/latest/server_development/index.html#registering-provider-implementations
